version: 2.1

setup: true

orbs:
  c: circleci/continuation@1.0.0

jobs:
  say-hello:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run: circleci config pack .circleci/ci_config > .circleci/merged.yml
      - c/continue:
          configuration_path: .circleci/merged.yml

workflows:
  say-hello-workflow: 
    jobs:
      - say-hello
